---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.4
    driver:
      box: centos-5.4-x64
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[analog::default]
    attributes:
